### ISSUE TITLE
Windowing

### ISSUE THREAD

**Issue by VictorAlbertsson** [zyrolasting/racket-vulkan#12]
I wanted to try this library but couldn't find any way to draw to a window, am I missing something or is that not implemented yet?

From what I found the Racket windowing library only support OpenGL is there any work-around?

**Comment by zyrolasting** [comment]
Vulkan does not provide functions to integrate directly with windowing systems. That's normally handled via extensions provided by libraries like GLFW. https://vulkan-tutorial.com uses GLFW for its examples.

You can grab some Racket FFI bindings for GLFW from https://github.com/hsalokor/rkt-glfw, then use it with this library.

**Comment by VictorAlbertsson** [comment]
Thank you for your help, maybe this could be added to the README or some example but otherwise looking forward to experimenting with this library!

**Comment by zyrolasting** [comment]
It would likely be in a future example. Thanks for the feedback.
