### ISSUE TITLE
vkDestroyInstance segfaults on 64bit CentOS 

### ISSUE THREAD

**Issue by raydialow** [zyrolasting/racket-vulkan#13]
calling vkDestroyInstance with a successfully created vkInstance segfaults everytime. All my mallocs are raw, so I don't think the GC is freeing the instance prematurely. In fact, testing the vkInstance pointer before hand confirms it is not nullptr. vkDestroyInstance does not throw any exceptions. Just segfaults and dies. It's possibly an upstream issue?

**Comment by zyrolasting** [comment]
I ran `minimal/examples.rkt` without issue on a 64bit Fedora (albeit the VK constants shouldn't be symbols anymore). I'm assuming our distributions are similar enough to rule that out as the issue.

> I don't think the GC is freeing the instance prematurely

I ran into opaque segfaults when setting up debug callbacks before. Is this a SIGSEGV MAPERR? In any case you may benefit from [this part of my userlist discussion](https://groups.google.com/d/msg/racket-users/Q7uAmFHHrz0/TfGw8OQPAwAJ). From what I recall, there are complications with the GC tracking memory changes with an attached debugger. Earlier emails in that thread also go over callbacks re: multiple OS threads, but that might only be relevant if you are using custom (de)allocators.

**Comment by raydialow** [comment]
Not using any allocation callbacks. A lack of external sync can cause issues. So I waited a full minute for any threads running on the Instance after creation to complete, *then* I called vkDestroyInstance on it and it still segfaulted.

**Comment by raydialow** [comment]
Yes, it is a SIGSEGV MAPERR. 
Closing this because I was passing vkDestroyInstance a pointer to the instance instead of the instance. It works now.
Just User Error over here, please disregard! :)
