### ISSUE TITLE
Problem with ravk --latest generate unsafe

### ISSUE THREAD

**Issue by Hectarea1996** [zyrolasting/racket-vulkan#15]
I'm using Windows 10 Home and Racket 7.9. Using the command `ravk --latest generate unsafe > unsafe.rkt` gives me the following error:

    car: contract violation
      expected: pair?
      given: #f

The command `ravk generate unsafe > unsafe.rkt` works fine.

**Comment by zyrolasting** [comment]
Unfortunately this is just part of the maintenance burden for this project. If the spec makes a breaking change, then `--latest` will fail depending on what the Khronos Group did. I'm not sure how long it will take to fix this one, but thanks for bringing it to my attention.

**Comment by zyrolasting** [comment]
When ready, please verify that #18 resolves your issue?

**Comment by Hectarea1996** [comment]
It works perfectly. Thank you!
