### ISSUE TITLE
ffi-lib: could not load foreign library path: vulkan.dll

### ISSUE THREAD

**Issue by Hectarea1996** [zyrolasting/racket-vulkan#20]
The unsafe.rkt file looks for a vulkan.dll file in Windows. Actually, the [documentation](https://vulkan.lunarg.com/doc/view/1.2.170.0/windows/loader_and_layer_interface.html#user-content-abi-versioning) says the vulkan loader in Windows is vulkan-1.dll.

The user has to change this name in the unsafe.rkt file.

Also, the [racket docs](https://docs.racket-lang.org/vulkan/Setup.html) says unsafe.rkt needs vulkan1.dll in Windows. This can be confusing for Windows users (I was).

Example after installing vulkan package:

    #lang racket/base

    (require vulkan/unsafe)

This throws:

    ffi\unsafe.rkt:131:0: ffi-lib: could not load foreign library path: vulkan.dll 
    system error: The specified module could not be found.; win_err=126

**Comment by zyrolasting** [comment]
Thanks! See #21

**Comment by Hectarea1996** [comment]
It works! Thank you!
